name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main
  # Cung cấp nút để chạy thủ công từ Github
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://kkoi31:$HF_TOKEN@huggingface.co/spaces/kkoi31/first_space main
